### ISSUE TITLE
i can't figure out how to compare two arrays! 

### ISSUE THREAD

**Issue by icusick** [icusick/project1#4]
i wrote a function that checks to see if the length is the same and each value: 

```
var isItTheSame = (thirdArray.length == fourthArray.length) && thirdArray.every(function(element, index) {
    return element === fourthArray[index]; 
});
```

it seemed to be working because it returned true on a  bunch of different arrays i tried out (and returned false if they were not the same) but it's returning false on my computer and player arrays! but i'm positive they are the same, i checked each element they all returned "true". usually the problem is with my code but because this seems to be working with every other array, i'm not sure what to do!

**Comment by icusick** [comment]
nevermind. i figured out another way. a very sloppy way, but it works.

**Comment by phlco** [comment]
:raised_hands:
